# Generated by Django 5.0.7 on 2024-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('img', models.ImageField(upload_to='')),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
